// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllRole() {
  return window['go']['backend']['App']['GetAllRole']();
}

export function GetCopyByDate(arg1, arg2) {
  return window['go']['backend']['App']['GetCopyByDate'](arg1, arg2);
}
