// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetAllRole():Promise<Array<string>>;

export function GetCopyByDate(arg1:string,arg2:string):Promise<Array<backend.CopyRecord>>;
